version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - tests
  tests:
    build:
      context: .
      dockerfile: Dockerfile.tests
